import React, { useState } from 'react';
import { AlertTriangle, ChevronDown, ChevronUp, ShieldAlert } from 'lucide-react';

interface MedicalDisclaimerProps {
  compact?: boolean;
}

export const MedicalDisclaimer: React.FC<MedicalDisclaimerProps> = ({ compact = false }) => {
  const [expanded, setExpanded] = useState(false);

  if (compact) {
    return (
      <div className="bg-amber-950/30 border border-amber-500/30 rounded-lg p-3 text-xs text-amber-200/90 flex items-start space-x-2.5">
        <ShieldAlert className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
        <div>
          <span className="font-semibold text-amber-300">Research & Screening Disclaimer:</span> This AI system is intended for research and screening support only. It is not a medical diagnosis and should not replace examination or advice from a qualified eye-care professional.
        </div>
      </div>
    );
  }

  return (
    <div className="bg-gradient-to-r from-amber-950/40 via-surface-900/60 to-amber-950/40 border border-amber-500/30 rounded-xl p-4 sm:p-5 shadow-lg shadow-amber-950/20 backdrop-blur-sm">
      <div className="flex items-start justify-between">
        <div className="flex items-start space-x-3">
          <div className="p-2 rounded-lg bg-amber-500/10 border border-amber-500/20 text-amber-400 shrink-0">
            <AlertTriangle className="w-5 h-5" />
          </div>
          <div>
            <h4 className="text-sm font-semibold text-amber-300 flex items-center gap-2">
              Clinical & Research Advisory Notice
              <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded bg-amber-500/20 text-amber-300 border border-amber-500/30">
                Screening Support Only
              </span>
            </h4>
            <p className="text-xs sm:text-sm text-surface-300 mt-1 leading-relaxed">
              This AI system is intended for <strong>research and screening support only</strong>. It is <strong>not a medical diagnosis</strong> and should not replace examination or advice from a qualified ophthalmologist or optometrist.
            </p>
          </div>
        </div>
        <button
          onClick={() => setExpanded(!expanded)}
          className="text-surface-400 hover:text-amber-300 p-1.5 rounded-lg hover:bg-surface-800 transition-colors ml-2 shrink-0"
          title={expanded ? "Collapse details" : "Expand details"}
        >
          {expanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </button>
      </div>

      {expanded && (
        <div className="mt-3 pt-3 border-t border-amber-500/20 text-xs text-surface-400 space-y-1.5 pl-11">
          <p>
            • The predictions and Grad-CAM attention overlays generated by EfficientNet-B3 represent computational activations and must not be used as the sole basis for clinical treatment decisions.
          </p>
          <p>
            • The referable diabetic retinopathy cutoff threshold is configured at <span className="text-amber-300 font-mono">0.13</span> for high sensitivity screening prioritization.
          </p>
          <p>
            • All patients suspected of diabetic eye disease should undergo comprehensive dilated eye examinations by accredited healthcare specialists.
          </p>
        </div>
      )}
    </div>
  );
};
